name: CD

on: 
    workflow_dispatch:

env:
  IMAGE_NAME: "web"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build & push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker build . --build-arg BUILD_CONFIGURATION=Release --file Dockerfile --tag $IMAGE_ID
        docker push $IMAGE_ID

    - name: Copy files via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infrastructure/prod.env,infrastructure/docker-compose.yml,infrastructure/docker-compose.prod.yml"
        target: "/home/${{ secrets.VPS_USER }}"
    
    - name: Run docker compose
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
            cd /home/${{ secrets.VPS_USER }}/infrastructure
            sed -i 's/DATABASE_PASS=.*/DATABASE_PASS=${{ secrets.DB_PASS }}/' prod.env
            sed -i 's/IMAGE_TAG=.*/IMAGE_TAG=${{ github.sha }}/' prod.env
            cat prod.env
            mv prod.env .env
            docker-compose -f docker-compose.prod.yml up -d