name: CD

on: 
    workflow_dispatch:

env:
  IMAGE_NAME: "web"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Container image
      run: docker build . --build-arg BUILD_CONFIGURATION=Release --file Dockerfile --tag ${{ env.IMAGE_NAME }}

    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push $IMAGE_ID

    # Step 4: Upload docker-compose.yml to remote server
    # - name: Upload Docker Compose File to Remote Server
    #   uses: appleboy/scp-action@v0.2.3
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     source: ./docker-compose.yml
    #     target: /home/${{ secrets.REMOTE_USER }}/docker-compose.yml

    # # Step 5: SSH into remote server and run Docker Compose
    # - name: Deploy App on Remote Server
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /home/${{ secrets.REMOTE_USER }}
    #       docker compose pull
    #       docker compose up -d
