name: CD

on: 
    workflow_dispatch:

env:
  IMAGE_NAME: "web"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build & push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker build . --build-arg BUILD_CONFIGURATION=Release --file Dockerfile --tag $IMAGE_ID
        docker push $IMAGE_ID

    - name: Copy files via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infrastructure/docker-compose.yml,infrastructure/docker-compose.prod.yml,prod.env"
        target: "/home/${{ secrets.VPS_USER }}"

    # # Step 5: SSH into remote server and run Docker Compose
    # - name: Deploy App on Remote Server
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /home/${{ secrets.REMOTE_USER }}
    #       docker compose pull
    #       docker compose up -d
