name: CD

on: 
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Subsitute variables in appsettings.json
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/appsettings.json'
      env:
        ConnectionStrings.BlogDbContext: ${{ secrets.DB_CONNECTION_STRING }}
        Email.SendGridKey: ${{ secrets.MAIL_SENDGRID_API_KEY }}  
        Email.SenderAddress: ${{ vars.MAIL_SENDER_ADDRESS }}  
        Email.SenderName: ${{ vars.MAIL_SENDER_NAME }}  
      
    - name: Build & push WEB docker image
      run: |
        WEB_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/web:${{ github.sha }}
        WEB_IMAGE_ID=$(echo $WEB_IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker build . --build-arg BUILD_CONFIGURATION=Release --file src/Blog.Server/Dockerfile --tag $WEB_IMAGE_ID
        docker push $WEB_IMAGE_ID

    - name: Build & push CLI docker image
      run: |
        CLI_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/cli:${{ github.sha }}
        CLI_IMAGE_ID=$(echo $CLI_IMAGE_ID | tr '[:upper:]' '[:lower:]')
        docker build . --build-arg BUILD_CONFIGURATION=Release --file src/Blog.Cli/Dockerfile --tag $CLI_IMAGE_ID
        docker push $CLI_IMAGE_ID

    - name: Copy docker files via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infrastructure/prod.env,infrastructure/docker-compose.yml,infrastructure/docker-compose.prod.yml"
        target: "/home/${{ secrets.VPS_USER }}"
        strip_components: 1
    
    - name: Run docker compose
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
            cd /home/${{ secrets.VPS_USER }}
            sed -i 's/DATABASE_PASS=.*/DATABASE_PASS=${{ secrets.DB_PASS }}/' prod.env
            sed -i 's/IMAGE_TAG=.*/IMAGE_TAG=${{ github.sha }}/' prod.env
            sed -i 's/CERT_PASS=.*/CERT_PASS=${{ secrets.CERT_PASS }}/' prod.env
            cat prod.env
            mv prod.env .env
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
