name: CI

on: 
    push: 
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up .Net
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Ng build
              run: npm install && npm run build
              working-directory: ./src/blog.client

            - name: Ng lint
              run: npm run lint
              working-directory: ./src/blog.client
                
            - name: Dotnet build
              run: dotnet build --configuration Release

            - name: Dotnet test
              run: dotnet test --configuration Release --no-build

            - name: Dotnet format
              run: dotnet format -v detailed --verify-no-changes