name: CI

on: 
    push: 
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up .Net
              uses: actions/setup-dotnet@v4
              with:
                global-json-file: global.json

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Npm install
              run: npm install
              working-directory: ./src/Blog.Clients.Web.UI

            - name: Npm lint
              run: npm run lint
              working-directory: ./src/Blog.Clients.Web.UI

            - name: Npm build
              run: npm run build
              working-directory: ./src/Blog.Clients.Web.UI

            - name: Dotnet format
              run: dotnet format -v detailed --verify-no-changes
                
            - name: Dotnet build
              run: dotnet build --configuration Release

            - name: Dotnet test
              run: dotnet test --configuration Release --no-build

