name: CI

on: 
    push: 
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        services:
          docker:
            image: docker
            options: --privileged # Required to run Docker-in-Docker
            ports:
              - 2375:2375
            env:
              DOCKER_TLS_CERTDIR: "" # Disable TLS for Docker-in-Docker

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up .Net 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                
            - name: Dotnet build
              run: dotnet build --configuration Release

            - name: Dotnet test
              env:
                DOCKER_HOST: "tcp://localhost:2375" # Point Testcontainers to the Docker service
              run: dotnet test --configuration Release --no-build

            - name: Dotnet format
              run: dotnet format -v detailed --verify-no-changes